### ISSUE TITLE
Juntar los pasos de lo que implica firmar el pdf

### ISSUE THREAD

**Issue by jbbenavidesr** [Cristrian/cyber-signature#4]
La interfaz de firma se encarga de coordinar el flujo para poder firmar el pdf. 

Esta función recibe un pdf abierto en modo `'rb'`  que es el archivo de entrada:

1. Genera un par de llaves publica y privada. (A futuro se puede pensar en que el usuario la entregue, pero por ahora no.) 
2. Crea una copia del pdf a la que adiciona una página con la información de la firma #1 
3. Genera la firma digital de este nuevo pdf con la página adicional #3 
4. Agrega la firma y la llave publica a la metadata del documento. #2 

Finalmente, la función retorna este nuevo pdf que incluye la página nueva y la firma en la metadata.

**Comment by Cristrian** [comment]
Está, menos el 4
